{% set name = "wagtail-metadata" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-metadata-{{ version }}.tar.gz
  sha256: 48cbc9dab91cbe2241383e0657e92cc703629e1bc1f8e890ddaf09ffdf65515d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - wagtail >=3.0,<4.0

test:
  imports:
    - wagtailmetadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neon-jungle/wagtail-metadata
  summary: A tool to assist with metadata for social media.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
