{% set name = "wagtail-metadata" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-metadata-{{ version }}.tar.gz
  sha256: 3b9109928bad53306b21b64cf9205d84cbb88fc625bac0a38305bebb9c26e64a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - wagtail >=3.0,<4.0

test:
  imports:
    - wagtailmetadata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neon-jungle/wagtail-metadata
  summary: A tool to assist with metadata for social media.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
